### PR TITLE
Performance update

### PR DESCRIPTION
**Pull request by rpropst**
Updating project to support latest Laravel and Sentry versions
Added performance tracking

### CODE REVIEW

**Comment by rpropst** [comment]
https://sentry.io/organizations/testorg-az/issues/2072723529/?project=5529609&query=is%3Aunresolved

Generated from REACT front-end

**Comment by thinkocapo** [comment]
Can you put a link to the Transaction for /checkout instead of the Error?
I see its trace value (tag) was `trace:2caef8d98b5043b79ca4dd51fc98b75c`, so there should be a Transaction with the same trace value.

Are transactions generated for when you hit the /handled and /unhandled routes?

@rpropst

**Comment by thinkocapo** [comment]
If those don't work then could you try adding a /helloworld or /success endpoint (that doesn't throw an error) that returns a 200 response?

For instance in our tracing demo, the Flask api has:
```
# https://github.com/sentry-demos/tracing/blob/master/flask/app.py#L36
@app.route('/success', methods=['GET'])
def success():
    response = make_response("success")
    return response
```
and this is [the transaction](https://sentry.io/organizations/testorg-az/discover/python-test:f6999583fdf64347b5f1d98c256ce8b8/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=5260888&query=&sort=-timestamp&statsPeriod=24h&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1) from the above /success endpoint.

Richard could you experiment with something like that but in PHP?

If you could update the PR description with what are the endpoints we are Testing and expecting to produce transactions for, that'd be great. Certainly possible that some things don't capture exactly the same the way they due in Flask, but as long as we get some working (documented as tested) then that's okay.

@ndmanvar unless you have ideas on where you want to see transactions? Same as Flask demo? If so, then we need Transactions on:

/pageload (I don't think our Laravel demo even has a Route::get('/') for pageload yet, so maybe could skip that)
/checkout (I think this should be our minimum goal, _hopefully_ we don't have to add any manual instrumentation for this, unless we want individualized Spans appearing [like they do in flask](https://github.com/sentry-demos/tracing/blob/master/flask/app.py#L88-L98))

**Comment by rpropst** [comment]
> Can you put a link to the Transaction for /checkout instead of the Error?
> I see its trace value (tag) was `trace:2caef8d98b5043b79ca4dd51fc98b75c`, so there should be a Transaction with the same trace value.
> 
> Are transactions generated for when you hit the /handled and /unhandled routes?
> 
> @rpropst

/checkout
https://sentry.io/organizations/testorg-az/performance/summary/?project=5529609&query=trace%3A2caef8d98b5043b79ca4dd51fc98b75c&statsPeriod=30d&transaction=checkout&unselectedSeries=p100%28%29

/handled (from postman)
https://sentry.io/organizations/testorg-az/performance/summary/?project=5529609&query=&statsPeriod=24h&transaction=handled&unselectedSeries=p100%28%29

/unhandled (from postman)
https://sentry.io/organizations/testorg-az/performance/summary/?project=5529609&query=&statsPeriod=1h&transaction=unhandled&unselectedSeries=p100%28%29

**Comment by rpropst** [comment]
I've added a `success` endpoint

https://sentry.io/organizations/testorg-az/performance/r2r-laravel:030e9c61bbde4149a2fd7960e9d018db/?project=5529609&query=&statsPeriod=24h&transaction=success&unselectedSeries=p100%28%29

**Comment by thinkocapo** [comment]
Documenting that the same Trace Id appears on both the error and the transaction
https://sentry.io/organizations/testorg-az/discover/results/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&query=trace%3A2caef8d98b5043b79ca4dd51fc98b75c&sort=-timestamp&statsPeriod=7d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1

Documenting that we did not manually instrument anything for /checkout so all you'll see is:
image

We can manually instrument at a later time, to make it resemble the sentry-demos/tracing's Flask /checkout endpoint? Or we do it now.

@rpropst

**Comment by thinkocapo** [comment]
go for the merge! @rpropst

**Pull request merged**
